Repository Gamify-IT/crosswordpuzzle-backend, pull requests merged in 2022-07, with the labels that each got.

#1 add initial crosswordpuzzle backend
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  README.md
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/crosswordservice/CrosswordServiceApplication.java
  src/main/java/com/crosswordservice/baseClasses/Configuration.java
  src/main/java/com/crosswordservice/baseClasses/Crossword.java
  src/main/java/com/crosswordservice/baseClasses/Intersection.java
  src/main/java/com/crosswordservice/baseClasses/Question.java
  src/main/java/com/crosswordservice/controller/CrosswordController.java
  src/main/java/com/crosswordservice/crosswordchecker/CrosswordChecker.java
  src/main/java/com/crosswordservice/crosswordchecker/CrosswordGenerator.java
  src/main/java/com/crosswordservice/repositories/ConfigurationRepository.java
  src/main/java/com/crosswordservice/repositories/QuestionRepository.java
  src/main/resources/application.properties
  src/test/java/com/crosswordservice/CrosswordServiceApplicationTests.java
Labels: feature

#2 add sonar
  .github/workflows/sonarqube-build.yml
  sonar-project.properties
Labels: maintenance

#8 Fix bugs in CrosswordController
  src/main/java/com/crosswordservice/controller/CrosswordController.java
  src/main/java/com/crosswordservice/repositories/QuestionRepository.java
  src/main/resources/application.properties
Labels: bug

#11 add dockerfile
  .github/workflows/deploy-docker-image-on-release.yml
  Dockerfile
  README.md
  pom.xml
  src/main/java/com/crosswordservice/crosswordchecker/CrosswordGenerator.java
  src/main/resources/application.properties
Labels: feature

#13 fix code smells
  src/main/java/de/unistuttgart/crosswordbackend/controller/ConfigController.java
  src/main/java/de/unistuttgart/crosswordbackend/crosswordchecker/CrosswordGenerator.java
  src/main/java/de/unistuttgart/crosswordbackend/data/Crossword.java
  src/test/java/de/unistuttgart/crosswordbackend/CrosswordServiceApplicationTests.java
Labels: maintenance
